version: 2.1

executors:
  default:
    docker:
  # ビルド済みイメージ：https://circleci.com/docs/ja/2.0/circleci-images/
        - image: circleci/node:10-browsers
commands:
  restore_modules:
    steps:
      - restore_cache:
          name: Restore node_modules
          key: repo-{{ checksum "front/src/package.json" }}
  save_modules:
    steps:
      - save_cache:
          name: Save node_modules
          key: repo-{{ checksum "front/src/package.json" }}
          paths: 
            - ~/workspace/front/src/node_modules
  build_storybook:
    steps:
      - run: 
          name: sotrybookをビルド
          command: npm run build-storybook

jobs:
  setup: 
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install

  deploy_storybook:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - build_storybook
      - run:
          name: deploy
          command: node ./scripts/deploy.js

workflows:
  build_test:
    jobs:
      - deploy_storybook
